- name: 准备 Docker 相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - /etc/docker
  - "{{ docker_storage_dir }}"

- name: 渲染 Docker 配置
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0644

- name: 重新加载 daemon
  systemd:
    daemon_reload: yes

- block:
  - name: 清理 iptables
    shell: >
      iptables -F &&
      iptables -X &&
      iptables -F -t nat &&
      iptables -X -t nat &&
      iptables -F -t raw &&
      iptables -X -t raw &&
      iptables -F -t mangle &&
      iptables -X -t mangle

  - name: 启动/重启 Docker
    service:
      name: docker
      state: restarted
      enabled: yes
  when: '"running" not in container_runtime_already_running.stdout'

- name: 设置 Docker 开机自启
  service:
    name: docker
    state: started
    enabled: yes

- name: 添加当前用户到 Docker 用户组
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- block:
  - name: 确认远程目录是否存在
    file:
      path: "{{ offline_images_dest|dirname }}"
      state: directory
      mode: 0755
  - name: 分发所需的容器镜像
    copy: 
      src: "{{ offline_images_src }}"
      dest: "{{ offline_images_dest }}"
      mode: 0755
  - name: 加载所需的容器镜像
    shell: "docker load -i {{ offline_images_dest }}"
  when: install_mode != 'online'