- name: 判断 Docker 是否早已安装并运行
  shell: >
    systemctl status docker | grep running || echo "NOT RUNNING"
  register: container_runtime_already_running
  when: container_runtime == 'docker'

- name: 判断 Containerd 是否早已安装并运行
  shell: >
    systemctl status containerd | grep running || echo "NOT RUNNING"
  register: container_runtime_already_running
  when: container_runtime == 'containerd'

# 系统基础软件环境
- include_tasks: "{{ container_runtime }}/centos.yml"
  when: 
  - ansible_distribution in [ 'CentOS','RedHat' ]
  - '"running" not in container_runtime_already_running.stdout'

- include_tasks: "{{ container_runtime }}/debian.yml"
  when: 
  - ansible_distribution in [ 'Ubuntu','Debian' ]
  - '"running" not in container_runtime_already_running.stdout'

# 公共系统参数设置
- include_tasks: "{{ container_runtime }}/common.yml"